apache/arrow-rs-object-store

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/audit.yml
.github/workflows/dev.yml
.github/workflows/dev_pr.yml
.github/workflows/object_store.yml
.github/workflows/rust.yml
.github/workflows/take.yml
dev/release/run-rat.sh

- Part of https://github.com/apache/arrow-rs-object-store/issues/2
This PR ports relevant files from https://github.com/apache/arrow-rs/tree/main/.github/ to this repo

Port `.github` templates and checks to arrow-rs-object-store crate

---

.asf.yaml
.github/workflows/object_store.yml
dev/release/check-rat-report.py
dev/release/rat_exclude_files.txt

- Part of https://github.com/apache/arrow-rs-object-store/issues/2
- Follow on to https://github.com/apache/arrow-rs-object-store/pull/6
I am trying to get the CI jobs working
Update the homepage listed in asf.yml to be the crates.io page
Add missing license check files

Tweaks: homepage and fix RAT

---

CONTRIBUTING.md
README.md

- Part of https://github.com/apache/arrow-rs-object-store/issues/2
There is information in the arrow-rs repository's [Readme.md](https://github.com/apache/arrow-rs/blob/166cc38fd1d33acb8ebc57c780724c953fe5790d/README.md) that refers to object_store so let's bring it over
Move content from arrow-rs readme to object_store
Docs

Update README.md and Contributing guidelines

---

.github/dependabot.yml

None.
The dependabot config can be updated.
Removed `/object_store` path config.
No.

Update dependabot config after repo move

---

Cargo.toml
src/aws/dynamo.rs
src/azure/client.rs
src/client/backoff.rs
src/client/dns.rs
src/integration.rs
src/upload.rs
src/util.rs

- Closes #5.
https://rust-random.github.io/book/update-0.9.html
The required changes to migrate from `0.8` to `0.9`.
`rand` dependency bumped to `0.9`.

Bump `rand` to 0.9

---

CONTRIBUTING.md
src/client/builder.rs

- Closes #320 
https://github.com/apache/arrow-rs/pull/7183 Changed the way the query string is serialized from:
```
azurebase.com/path?comp=list&restype:container
```
to:
```
azurebase.com/path?&comp=list&restype:container # Note the leading & after the ?
```
That data is encoded into `application/x-www-form-urlencoded` form, which is parsed according to [this](https://url.spec.whatwg.org/#urlencoded-parsing) spec. The `Url` crate ignores empty values (correctly) when parsing the underlying string in `Url::query_pairs`, but that means we sign the "wrong" string. The fix here basically tells is to serialize the query params as a suffix to the path, which is assumed to be encoded correctly.
I really think this behavior is mostly an Azure oddity/bug, but its much easier to fix it here than …

Fix query parameter signing in Azure

---

src/gcp/builder.rs
src/gcp/client.rs
src/gcp/credential.rs

Closes https://github.com/apache/arrow-rs-object-store/issues/302.
- Add `skip_signature` config parameter
- Add `with_skip_signature` to `GoogleCloudStorageBuilder`
- Add `CredentialExt` in `src/gcp/credential.rs`, similar to what already exists for AWS in `src/aws/credential.rs`. This allows for easily calling `with_bearer_auth` in the request builder chain without having to do an `if/else` to handle `credentials` being `None` there.
**Questions**
- How should I test this? I looked for other existing tests for `skip_signature` and it looks like the one existing one for AWS is ignored: https://github.com/apache/arrow-rs-object-store/blob/e975177814778b711e11b048bb5c703d2b893427/src/aws/mod.rs#L690-L714
I was able to successfully test this in the obstore Python bindings …

Enable anonymous access to GCS buckets

---

.cargo/config.toml
.github/workflows/ci.yml
.github/workflows/object_store.yml
Cargo.toml
src/client/body.rs
src/client/connection.rs
src/client/mod.rs
src/client/retry.rs
src/parse.rs
src/prefix.rs
src/throttle.rs
tests/http.rs

- Closes https://github.com/apache/arrow-rs/issues/7227.
Target-gated wasm32-unknown-unknown reqwest-based HttpConnector (with explicit handling surrounding non-Send, non-Sync futures).
wasm32-unknown-unknown users will need to add the `getrandom = { version = "*", features = ["js"] }` cargo entry if they aren't already using it. The alternative would be to feature flag in a similar manner to chrono, getrandom, zstd (i.e. 'js').

Support `object_store` with wasm: Default wasm32-unknown-unknown HttpConnector

---

README.md

[anda_object_store](https://github.com/ldclabs/anda-db/blob/main/rs/anda_object_store/README.md) is a Rust library that extends the functionality of the [object_store](https://docs.rs/object_store) crate with additional features like metadata management and encryption.
Integration Test: 
- MetaStore: https://github.com/ldclabs/anda-db/blob/main/rs/anda_object_store/src/lib.rs#L577
- EncryptedStore: https://github.com/ldclabs/anda-db/blob/main/rs/anda_object_store/src/encryption.rs#L902

chore: Add anda_object_store to README

---

.github/workflows/ci.yml
.gitignore
CONTRIBUTING.md
src/aws/mod.rs
src/client/builder.rs
src/client/http/body.rs
src/client/http/connection.rs
src/client/http/mod.rs
src/client/http/spawn.rs
src/client/mod.rs
src/client/retry.rs
src/lib.rs

- closes https://github.com/apache/arrow-rs-object-store/issues/13
Adds support for spawning reqwuests tasks to another Runtime. Credits to @tustvold, I simply added an additional connector in there to make it easier for others to integrate this in their code base.
- Port of https://github.com/apache/arrow-rs/pull/7253
Example:
```rust
let prefix = Path::parse(path)?;
let mut builder = MicrosoftAzureBuilder::new().with_url(url.to_string());
for (key, value) in config.iter() {
builder = builder.with_config(*key, value.clone());
}
let inner = builder
.with_retry(self.parse_retry_config(options)?)
.with_http_connector(SpawnedReqwestConnector::new(io_handle))
.build()?;
```
Allows a separation of cpu bound tasks and io bound tasks
- Adds a SpawnService
- Adds a SpawnedReqwestConnector
Only an …

feat: Add `SpawnService` and `SpawnedReqwestConnector` for running requests on a different runtime

---

src/gcp/credential.rs

* refresh token replaced by access token
Closes [#](https://github.com/apache/arrow-rs-object-store/issues/337).
Changes how the GCP Signing Auth retrieves the email, originally the token info endpoint was used with a refresh token whether behavior has changed on googles side or that was never functional is out of scope but now it generates a access_token using ADC then uses the access token to retrieve the email.
No.

Fix GCP signing token

---

src/aws/builder.rs
src/aws/credential.rs

Closes #282 
This PR extends the `AmazonS3Builder` so that it recognises and supports EKS Pod Identity credentials using the two environment variables:
- `AWS_CONTAINER_CREDENTIALS_FULL_URI`
- `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`
Previously, the builder only considered ECS task credentials (`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`), instance metadata, static credentials, or web identity tokens. Adding EKS Pod Identity support aligns it with modern Kubernetes IRSA setups, allowing pods to retrieve AWS credentials from an EKS endpoint without needing to mount AWS credentials directly.
1. **New Config Keys**
Adds `AmazonS3ConfigKey::ContainerCredentialsFullUri` and `AmazonS3ConfigKey::ContainerAuthorizationTokenFile` to the config-based approach, for parsing EKS Pod Identity settings. …

feat: add EKS Pod Identity support (#282)

---

.github_changelog_generator
CHANGELOG-old.md
CHANGELOG.md
Cargo.toml
README.md
dev/release/README.md
dev/release/create-tarball.sh
dev/release/update_change_log.sh

- Part of https://github.com/apache/arrow-rs-object-store/issues/287
Time to release
Note this will be the first release after the object store code was moved into its own repo
- https://github.com/apache/arrow-rs/issues/6183
1. Update Changelog. See rendered version here: [prepare_0.12.1/CHANGELOG.md](https://github.com/alamb/arrow-rs-object-store/blob/alamb/prepare_0.12.1/CHANGELOG.md)
2. Update version
3. Update scripts to work (hopefully) in new repo

Prepare for 0.12.1 release

---

src/client/http/connection.rs

Closes #350.
We want object_store to retry the request in case the connection closed abruptly.
Map `std::io::ErrorKind::ConnectionReset` -> `HttpErrorKind::Interrupted`
No.

fix: treat TCP reset as a retryable error

---

src/http/client.rs
src/http/mod.rs

Closes #365.
Allows for better error handling of HTTP statuses, and makes it consistent with how the S3/Azure/GCP clients handles RetryError.
Adjust implementation of `impl From<http::client::Error> for crate::Error` to use RetryError::error when possible.
Most RetryError cases just returned `crate::Error::GenericError` before, now they'll return the crate::Error that matches the RetryError

Return Non-Generic Errors from HttpStore

---

src/aws/client.rs
src/aws/mod.rs
src/azure/client.rs
src/azure/mod.rs
src/client/list.rs
src/gcp/client.rs
src/gcp/mod.rs
src/integration.rs
src/lib.rs
src/list.rs

Closes #291
Closes #327.
Relates to #361
Relates to #295 
There is a desire to expose listing APIs even closer to the object stores themselves, either to support custom pagination or non-path-segment based listing.
Adds a PaginatedListStore in a similar vein to MultipartStore

Add PaginatedListStore

---

Cargo.toml

- Closes https://github.com/apache/arrow-rs-object-store/issues/357
I can't run `cargo publish` without doing this first
See subject
No, this affects testing and release, not users

Fix `cargo publish` by specifying version for wasm-bindgen-test

---

src/parse.rs

- Related to https://github.com/apache/arrow-rs-object-store/pull/375
When trying to understand https://github.com/apache/arrow-rs-object-store/pull/375 it was not clear to me what `parse_url_opts` did from the documentation alone. 
Update documentation, including examples

Improve parse_url_opts documentation

---

src/aws/client.rs
src/aws/dynamo.rs
src/aws/mod.rs
src/azure/client.rs
src/client/get.rs
src/client/http/body.rs
src/client/mock_server.rs
src/client/retry.rs
src/gcp/client.rs
src/http/client.rs

~_Draft as needs tests_~
Closes #15
With this PR we retry streaming get requests. Technically it is still possible to get response body errors on the other methods, however, I chose to just do get requests as these are the highest impact as they have the largest payloads, and we can always do the others later.

Retry streaming get requests (#15)

---

src/parse.rs

- Closes https://github.com/apache/arrow-rs-object-store/issues/398.
Is there a spec for each of these URL formats? In my usage of Azure so far it seems like Azure URLs like `https://blob.core.windows.net/` _always_ have the container as the first element of the URL path. Is that true? 
Refer to the tests updated in this PR and ensure that you agree with the edited versions of them.
Fixed parsing paths from Azure URLs.
Yes. Up to consideration whether this is a bug fix or a breaking change.

Fix azure path parsing

---

src/aws/builder.rs
src/aws/client.rs
src/aws/credential.rs
src/aws/precondition.rs
src/aws/resolve.rs
src/azure/builder.rs
src/azure/client.rs
src/azure/credential.rs
src/client/builder.rs
src/gcp/builder.rs
src/gcp/client.rs
src/gcp/credential.rs
src/local.rs
src/throttle.rs

None.
Clippy warnings.
Applied Clippy suggestions.
No.

chore: fix clippy 1.88 warnings

---

src/client/retry.rs

Closes #309
Closes #425
Status code 429 is what HTTP uses to indicate the client has sent too many requests in a given amount of time. It may sound counter-intuitive to retry in this situation, but that's why we use an exponential backoff mechanism. It gives the server the opportunity to recover, without failing the requests immediately.
The retry mechanism already works in object stores like S3 because they return a server error. But without this change, we are not handling GCS properly. GCS returns a client error `429 Too Many Requests` instead. This change enables retries on this response too.
A more advanced retry mechanism would use the optional response header `Retry-After`, but that is beyond the scope of this PR.

Retry requests when status code is 429

---

src/client/http/connection.rs
src/client/retry.rs

Closes #368.
As described in #368 connection reset errors aren't being retried due to them being identified as `HttpErrorKind::Unknown` rather than `HttpErrorKind::Interrupted`. This is because the `reqwest::Error` has kind unknown and its immediate source error is a generic `Request` error however if you continue following the error source we eventually get to a `std::io::ErrorKind::ConnectionReset` error.
Currently we stop refining the HTTP error kind once we've been able to downcast the error to either a `hyper::Error` or `std::io::Error` regardless of whether or not we were able to provide a more useful error kind.
This PR changes that so that we keep on refining until we are able to provide a more useful error kind (i.e. not unknown) or we run out of nested errors to check. Because …

Fix not retrying connection errors

---

src/client/http/spawn.rs

Spawn service was panicking when it was trying to write out the body to the channel.
This PR adjusts the spawn service so it doesn't panic, but instead just finishes off the task.
No
I think you should really ban the use of `unwrap` in any code in this project (besides tests).  You can do so with clippy pretty easily

Dont unwrap on body send

---

src/gcp/builder.rs

Closes #.
In general, all config keys have a `FromStr` implementation that allows either a store-prefixed parameter name, or the same name without the prefix. 
I.e. `"google_service_account"` and `"service_account"` are both valid string keys for `GoogleConfigKey::ServiceAccount`. 
But `"google_application_credentials"` does not follow this symmetry. It would be more predictable if it did.
Allow `"application_credentials"` as a string key for `GoogleConfigKey::ApplicationCredentials`.
Yes, new string allowed for config key.

Allow "application_credentials" in `impl FromStr for GoogleConfigKey`

---

src/aws/builder.rs

Given this is a small change, I did not think it was necessary to open an issue. I can do so if necessary.
These log messages are very noisy and it seems like they can be downgraded to debug.
Just downgrading log messages from info to debug
Users that would previously see `Using * credential provider` log messages with info level will not see them any more.

aws: downgrade credential provider info! log messages to debug!

---

README.md

- Related to https://github.com/apache/arrow-rs-object-store/issues/392
- RElated to https://github.com/apache/arrow-rs-object-store/issues/489
Let's plan for a 0.12.4 non-breaking release

Add version 0.12.4 release plan to README

---

src/azure/credential.rs

- Related to https://github.com/apache/arrow-rs-object-store/issues/489
- 
Rust 1.90 is released https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/ and clippy got smarter
I would like to have clean CI runs for the next release
Here is an example CI failure: https://github.com/apache/arrow-rs-object-store/actions/runs/17860331710/job/50789123954?pr=491
```
Checking object_store v0.12.4 (/__w/arrow-rs-object-store/arrow-rs-object-store)
error: unnecessary parentheses around closure body
--> src/azure/credential.rs:510:27
|
510 |         .filter(|&(k, _)| (k.as_str().starts_with("x-ms")))
|                           ^                              ^
|
= note: `-D unused-parens` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_parens)]`
help: remove these …
```

Fix for clippy 1.90

---

src/aws/client.rs

Closes #495 
Fixes error 411 when using S3 Client's multipart upload on GCS S3-compatible mode
Adding the Content-Length header in the create_multipart() request as GCS requires.
User won't see error 411 when using S3 Client's multipart upload on GCS S3-compatible mode

Add Content_length header to S3 create_multipart
